default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: postgres
  user: postgres


development:
  <<: *default
  database: v1moneyconvertion_development


test:
  <<: *default
  database: v1moneyconvertion_test

production:
  <<: *default
  database: v1moneyconvertion_production
  username: v1moneyconvertion
  password: <%= ENV['EXCHANGE_DATABASE_PASSWORD'] %>
